### ISSUE TITLE
Mistakable error message due to double slash characters

### ISSUE THREAD

**Issue by Michaelsy** [dokuwiki/dokuwiki#3903]
Mistakable error message due to double slash characters between `data` and `log`. See also [forum's post](https://forum.dokuwiki.org/d/20880/4).

> The logdir ('log') at `/<path-to-dokuwiki>/data//log` is not found, isn't accessible or writable. You should check your config and permission settings. Or maybe you want to run the installer?

\- Michael Sy.

**Comment by Klap-in** [comment]
https://codesearch.dokuwiki.org/xref/dokuwiki/inc/init.php#289-297
Default is without slash behind `data`-folder. https://codesearch.dokuwiki.org/xref/dokuwiki/conf/dokuwiki.php#23

Or is it overridden in preload.php? (e.g. in farm setup?)

**Comment by Michaelsy** [comment]
I was addressing pop, who may have more information.

If it is possible to create the double slash by a user input, could it perhaps be the best solution that such a misformat would be corrected automatically?

\- Michael Sy.

**Comment by pop-ch** [comment]
pop here.

> https://codesearch.dokuwiki.org/xref/dokuwiki/inc/init.php#289-297 Default is without slash behind `data`-folder. https://codesearch.dokuwiki.org/xref/dokuwiki/conf/dokuwiki.php#23
> 
> Or is it overridden in preload.php? (e.g. in farm setup?)

Sorry, I can't help very much here; I don't understand the code you quote.
My setup consists of one farmer with three animals. They were working perfectly fine until I upgraded the farmer to Igor. The farmer ran well after the upgrade, none of the animals did.

The actual text of the error message was: The logdir ('log') at /data/www/www209/wikis/freidorf/data//log is not found, isn't accessible or writable. (remainder omitted)

/data/www/www209/wikis/freidorf/data is the actual path to the data directory of the animal called freidorf. As it turned out, the  path in the error message should have read /data/www/www209/wikis/freidorf/data/log

**Comment by splitbrain** [comment]
I don't understand the problem. An additional slash doesn't make the path unusable. `/data/www/www209/wikis/freidorf/data//log` is exactly the same as `/data/www/www209/wikis/freidorf/data/log` from a filesystem point of view?

**Comment by pop-ch** [comment]
From the point of view of the developer, it may not matter at all if there are any extra slashes in any given path.
From the point of view of a naive user (such as myself) who lacks most of the basics of the Unix file system, Apache, PHP (to mention but a few of the things we should know about) the message with a seemingly garbled path to a missing directory is highly confusing.
In the particular case which led to this issue: I upgrade a farmer with some perfectly working animals. Due to some error, the animals cease working. The error documents itself with a 'funny' path to an apparently missing directory. I see no way to produce a directory with that path using FTP on server run by third party. The message is caused by an error. Hence, I have no way to tell if the message is indeed part of the error and should have shown additional path elements between the slashes.
As Michael has stated in the title of the issue: The error message is misleading, particularly to relative noobs.
