### ISSUE TITLE
Warning in Resendpwd.php

### ISSUE THREAD

**Issue by Miro-Collas** [dokuwiki/dokuwiki#4032]
PHP 8.1
Dokuwiki Release 2023-04-04a "Jack Jackrum"

I just happened to see this in logs:

```
2023-08-19 03:49:08E_WARNING: Trying to access array offset on value of type bool/home/fswiki/public_html/inc/Action/Resendpwd.php(152)
    #0 /home/fswiki/public_html/inc/Action/Resendpwd.php(152): dokuwiki\ErrorHandler::errorHandler(2, 'Trying to acces...', '/home/fswiki/pu...', 152)
    #1 /home/fswiki/public_html/inc/Action/Resendpwd.php(41): dokuwiki\Action\Resendpwd->resendpwd()
    #2 /home/fswiki/public_html/inc/ActionRouter.php(83): dokuwiki\Action\Resendpwd->preProcess()
    #3 /home/fswiki/public_html/inc/ActionRouter.php(48): dokuwiki\ActionRouter->setupAction('resendpwd')
    #4 /home/fswiki/public_html/inc/ActionRouter.php(60): dokuwiki\ActionRouter->__construct()
    #5 /home/fswiki/public_html/inc/actions.php(16): dokuwiki\ActionRouter::getInstance(true)
    #6 /home/fswiki/public_html/doku.php(126): act_dispatch()
    #7 {main}
```

**Comment by fiwswe** [comment]
That sounds familiar. See #3982.

Which auth plugin are you using? I think the authad plugin had bugs for example.

I started a [fix](https://github.com/fiwswe/dokuwiki/commit/e6af5171c3234eae16d4739ebd06e179fd7f444c) in my fork but I never sent a PR because the basic issue seems to be that auth plugins generally do not adhere to the API contract (exceptions may prove the rule) and there is no verification in place that they do either. This is a structural problem in DW. Small patches may mask the issue but this should be fixed at a different level IMHO.

Check out the comments for:
https://github.com/dokuwiki/dokuwiki/blob/0877de155d3e8cab1d6479cab1735cc2acd222ab/inc/Extension/AuthPlugin.php#L239:L254
and compare that to what the actual auth plugins return.

**Comment by Miro-Collas** [comment]
> That sounds familiar. See #3982.
> 
> Which auth plugin are you using? I think the authad plugin had bugs for example.

Plain Auth Plugin

**Comment by fiwswe** [comment]
Sorry, I seem to have mixed this up with another issue in my analysis.

The solution is in #3983 but has not been merged yet.

**Comment by Klap-in** [comment]
>
> I started a [fix](https://github.com/fiwswe/dokuwiki/commit/e6af5171c3234eae16d4739ebd06e179fd7f444c) in my fork but I never sent a PR because the basic issue seems to be that auth plugins generally do not adhere to the API contract (exceptions may prove the rule) and there is no verification in place that they do either. This is a structural problem in DW. Small patches may mask the issue but this should be fixed at a different level IMHO.
> 
Such issues are worth a separate issue report to discuss solutions.
