### ISSUE TITLE
RFC: use composer (correctly) for dev dependencies inside _test?

### ISSUE THREAD

**Issue by splitbrain** [dokuwiki/dokuwiki#4058]
We famously use composer "wrong" for DokuWiki by checking in our composer installed dependencies. This ensures that a checkout is immediately usable and avoids "leftpad" fails. I don't intend to change that in the foreseeable future.

However, we also have some dev-only dependencies which we currently install via composer in the `_test` directory. Namely PHPDomWrapper and it's requirements. We also check in those dependencies. I would like to propose changing that.

* no longer check in the `_test/vendor` directory
* require developers to run `composer install` in `_test` themselves
* add our development tooling to the `_test/composer.json`, namely
  * phpunit
  * phpcs
  * phpcbf
  * rector

I think this will make use of those tools easier (especially in case of rector which is not available as .phar).

Any objections?

**Comment by Klap-in** [comment]
At the moment I have issues with the phpunit setup. Might be due to mixture of versions from Ubuntu, phar, different php versions, etc. I’m in favor of one way for all tools. Via composer this seems feasible, so fine for me.

Sometimes I’m struggling with trying the different php versions, is it worth to consider adding these to the composer.json as well? Eventually with the config platform setting?

(This change would need an update of docs about unittests and composer.)
