### ISSUE TITLE
Update namespace templates for extensions

### ISSUE THREAD

**Issue by Klap-in** [dokuwiki/dokuwiki#4063]
The namespace templates for plugins (and for templates a little bit) are not well maintained, because they are not editable. 
Please could a server admin share the content of 
`plugin/_template.txt` and `template/_template.txt` (and eventually other relevant examples). Then an update can be made.

I would vote for adding the plugin https://www.dokuwiki.org/plugin:templatepagename such that we can rename `_template.txt` to `template` in the Configuration settings. (offtopic: I'm in favor of including this into the core as `_template.txt` is not maintainable by design).

This means that that the template overlaps with the plugin https://www.dokuwiki.org/plugin:template. Let we rename it to something different (e.g. template_old), as it seems not usable and is not maintained anymore.

**Comment by splitbrain** [comment]
I installed the plugin and renamed the templates (using the default names, since they don't clash easily with real pages):

- https://www.dokuwiki.org/config:c_template
- https://www.dokuwiki.org/plugin:c_template
- https://www.dokuwiki.org/template:c_template
- https://www.dokuwiki.org/dokuinstall:c_template
- https://www.dokuwiki.org/devel:event:c_template
 
For making namespace templates editable I would suggest a new issue. It needs a bit more discussion.

**Comment by Klap-in** [comment]
Thanks @splitbrain
