### ISSUE TITLE
lesserphp causes lots of deprecation log entries

### ISSUE THREAD

**Issue by mosource21** [dokuwiki/dokuwiki#4088]
DokuWIki 2023-04-04a "Jack Jackrum"
PHP v8.1.17
PHP Deprecated: preg_match(): Passing null to parameter 4 ($flags) of type int is deprecated in \vendor\marcusschwarz\lesserphp\lessc.inc.php on line 3739
This problem can make it look like DokuWiki is very unresponsive due to the tens of thousands of writes to the php_error.log file for every page display.

The following fixes the problem for me (change null to 0):

Line 3739: 		
change: if (preg_match($r, $this->buffer, $out, null, $this->count)) {
to:  if (preg_match($r, $this->buffer, $out, 0, $this->count)) {

Suggest fixing other similar occurrences (others have already been fixed - above and below must have been missed):

Line 3751:
change: while (preg_match(self::$whitePattern, $this->buffer, $m, null, $this->count)) {
to: while (preg_match(self::$whitePattern, $this->buffer, $m, 0, $this->count)) {

Line 3770:
change: $result = preg_match($r, $this->buffer, $out, null, $from);
to: $result = preg_match($r, $this->buffer, $out, 0, $from);

[A partial duplicate of #3948 but this has a more descriptive title and additional suggested fixes just in case anyone is searching for a solution.]

**Comment by fiwswe** [comment]
Ok, the issue is already filed as: MarcusSchwarz/lesserphp#23 and I agree your suggested patch would fix it. Maybe someone needs to submit a PR to help speed that along…

The version used in DokuWiki seems to be [0.6](https://github.com/MarcusSchwarz/lesserphp/releases/tag/v0.6.0) and confusingly the latest development seems to take place in the [0.6-dev](https://github.com/MarcusSchwarz/lesserphp/tree/0.6-dev) branch — though not much seems to be happening there. The [master](https://github.com/MarcusSchwarz/lesserphp/) branch seems rather outdated.


I have never seen similar messages in my error logs. So I suspect something in your particular setup triggers the bug. What template are you using? Which plugins did you add? Did you manually edit any *.less files?

If you want to figure out the trigger, something like `$ find /var/www/dokuwiki -name '*.less' -print` may help to find all of the potential *.less files if you are on a *NIX OS.

**Comment by Klap-in** [comment]
Dokuwiki combines all css and less files to one piece and parses that with the less parser. (So not only *.less files but also *.css files can (and do) contain less).

Maintenance of library is lacking in my view because most attention (and resources) go to a version maintained by mediawiki, but which is unfortunately incompatible with DokuWiki’s license (see https://github.com/dokuwiki/dokuwiki/issues/3398). Therefore it have to come mainly from us.

**Comment by StarArmy** [comment]
This issue took recently broke my web server by generating over 120 Gigabytes of deprecated log files and filling up all available disk space with these warnings. I had to disable deprecated logging to resume normal operation.

**Comment by splitbrain** [comment]
I guess we have to create our own fork of lesserphp. Unless we want to switch (again) to somebody else's fork. But it seems most of the somewhat active forks split off the timeline somewhere earlier: https://github.com/MarcusSchwarz/lesserphp/network

Consolidating this mess will be a pain.

**Comment by splitbrain** [comment]
fork and refactoring in progress at https://github.com/splitbrain/lesserphp
