### ISSUE TITLE
unable to create large posts

### ISSUE THREAD

**Issue by frostbane** [dokuwiki/dokuwiki#4092]
I can post small notes but when the text size reaches about 100k the page just refreshes and there is no error message. The network tab in the developer tools also don't show any errors.

If I manually create the text file and paste a large amount of text, I can see it on my wiki but I am unable to edit it.

**Comment by splitbrain** [comment]
100kb seems excessively large for a single wiki page. However there's nothing in DokuWiki that limits page sizes. Since you say a manually created file renders just fine, I don't think you're running into a memory issue either. Most likely culprit is a limit in PHP (check your php.ini) or your web server (check your web server config). Some distributions/servers have default limits in place, so if nothing is set, that default might be too low.

**Comment by fiwswe** [comment]
Well, I have wiki pages of 688K size and they work fine on this setup:
DokuWiki 2023-04-04a
Apache httpd 2.4.56
PHP 8.2.11 (PHP-FPM)
OpenBSD 7.3

**Comment by obw** [comment]
@splitbrain yes 100kb are normally Pages which are big, I use DoKuWiki for writing stories, which means I have Page with more than one Megabyte of text!

@frostbane I think your Problem is the configuration of your Server!

**Comment by frostbane** [comment]
I had to dig hard and deep. The server and container configurations were perfectly fine.

The problem was the missing `tmp` directory in the dokuwiki checkout.

Apparently if you `chroot` dokuwiki you need the `tmp` directory (like duh.) I don't know why it got deleted. Maybe because git does not monitor empty folders?

Just adding my solution in case somebody experiences the same problem,
