### ISSUE TITLE
Trying to access doku.php?id=start&do=admin&page=config fails if user has no mail set with authad plugin on Dokuwiki 2024-02-06 "Kaos"

### ISSUE THREAD

**Issue by TJuberg** [dokuwiki/dokuwiki#4190]
After upgrading to Dokuwiki 2024-02-06 "Kaos" we have some admin users who are unable to access administration - config settings
Theese are dedicated admin users, and do not have emails set in AD.

When accessing https://dokuwiki.url/doku.php?id=start&do=admin&page=config an error is shown to the user 
> ArgumentCountError: 4 arguments are required, 2 given
> An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the config plugin.

Warning logged is:
> PHP Warning:  Array to string conversion in /usr/share/dokuwiki/inc/Extension/PluginTrait.php on line 50, referer: https://dokuwiki.url/doku.php?id=start&do=admin

Logging the user out and back in again reveals
> PHP Warning:  Undefined array key "mail" in /usr/share/dokuwiki/lib/plugins/authad/auth.php on line 229, referer:  https://dokuwiki.url/doku.php?id=start&do=login
> PHP Warning:  Trying to access array offset on value of type null in /usr/share/dokuwiki/lib/plugins/authad/auth.php on line 229, referer: https://dokuwiki.url/doku.php?id=start&do=login

However no error is displayed to the user at any point here and the user can operate in the wiki without issues except for when trying to access config

Adding som debug output to PluginTrait.php reveals that key 'mail' is undefined in the array.

https://github.com/dokuwiki/dokuwiki/commit/a0d03045791d1a7a2ae869fea7b7f932f20405da seems to be potentially related, however I haven't had the time to research this further at present as it only affects admins, and seemingly admins without email (which we don't really want to have set on admins in our case)

**Comment by fiwswe** [comment]
At this time the contract for the `getUserData()` method **requires** it to return a `'mail'` array member. Not returning this data is thus a failure:

https://github.com/dokuwiki/dokuwiki/blob/ab86a1cdff274f08d0d99df074557be85357331c/inc/Extension/AuthPlugin.php#L237-L252

If it makes sense to have users (admins) without an email address (which I'm not sure is a good idea), then DokuWiki and all callers/consumers would need to be redesigned to deal with this.

[a0d0304](https://github.com/dokuwiki/dokuwiki/commit/a0d03045791d1a7a2ae869fea7b7f932f20405da) was actually meant to enforce parts of this contract because some consumers did not deal with missing data correctly. But it does not specifically check for the existence of the required fields.

Another alternative might be using a dummy value instead of a real email address. The contract only requires a `string` which could in theory be empty. (Whether the caller can deal with an empty string would need to be checked though.)

**Comment by TJuberg** [comment]
I have no problem with the justification and reasoning behind it if it is actually required for some reason. However having had this setup for quite some years now, I have yet to encounter any issues until this release.

My main problem is that its an undocumented change which at present locks admins out of the settings.
This specific one should have been caught in our own testing but the config section was not one validated, however, i cannot find a single other place in Dokuwiki that enforces email or throws users visible errors for these users.

Can log in fine, can access all other parts of Dokuwiki and function as it should, except the interface for managing the configuration. Strikes me as a bit odd.

We can work around this, but I expect others might be caught by this as well

**Comment by fiwswe** [comment]
As for how many others may be affected, I wouldn't know. IMHO not having an email address for a DokuWiki user could be considered quite unusual if not outright unsupported.

Actually I'm not sure why the upgrade to "Kaos" would change anything in your case. I don't think https://github.com/dokuwiki/dokuwiki/commit/a0d03045791d1a7a2ae869fea7b7f932f20405da would be the cause. But since I don't have any AD I can't test what happens. The commit only makes the method return `false` instead of `[]` in some cases. Does
https://github.com/dokuwiki/dokuwiki/blob/ab86a1cdff274f08d0d99df074557be85357331c/lib/plugins/authad/auth.php#L203
maybe return `false` now when it didn't before?

There were other commits that affected the authad Plugin since "Jack Jackrum". I think they where mostly code style fixes but maybe something was inadvertently modified that changed the behaviour of the Plugin?

Anyway since @splitbrain seems to be the author of the API contract, I'm sure he had his reasons for writing it the way he did. Are these reasons still valid today? If not, someone could submit a PR to implement an API that is a bit less strict.
* The password reset emails are probably moot when using authad. (But since I have never used authad I'm not sure? From a security point of view it might not be a good idea to allow a web application like DokuWiki to change AD passwords. And if that is so then there don't need to be any reset password emails.)
* Subscribing to changes would require an email address though. And admins may want to do that.
* Some plugins display meta data about the creator/editor of a page. That data sometimes contains a link to the email address which would break if there is none.

Or you could submit a PR that modifies the authad Plugin to return some `string` in `['mail']` that doesn't break anything else even when AD does not return any data for this field.

**Comment by splitbrain** [comment]
We basically assume everywhere that a mail is set for each user. Previous PHP versions silently ignore access to non-existing array keys. With PHP 8 that's no longer the case.

I think we should make this more clear by not allowing users to log in without an email address returned in getUserData.

**Comment by TJuberg** [comment]
I havent had the time to spend more time on tracking down why this doesn't trigger at earlier points like login unfortunately.

The way I see it one of two things would be more ideal than what happens today

Either, given that no actual functionality that does not involve sending an email to an user (that I have found), add a warning if trying to subscribe to changes or similar where an email would be required.

Or, consider hard failing early, i.e on login, when an AD user without an email (valid in AD, and not uncommon in more closed environments where you don't really want administrative users to have an email set), but give a more reasonable output indicating that both username, name, email and in the event of groups beeing required, that groups are required.

There are some other possible variations of course. But I'll leave it up to the team if you want to do something about this admittedly less common case or not. I won't argue against a WONTFIX.

**Comment by TJuberg** [comment]
Seems that #4193 and https://github.com/dokuwiki/dokuwiki/commit/2c978aed5aecf1f9f21a94e0bfa7e66c19141dd1 was the same issue I was seeing.

Works now following upgrade
