### ISSUE TITLE
"draft saved" notification makes edit field too narrow on mobile screens

### ISSUE THREAD

**Issue by JohaJung** [dokuwiki/dokuwiki#4229]
### The problem

When editing a page on mobile and pressing "preview", there is the line mentioning when The draft was last saved. Unfotunately, the layout is very broken here making the text field very small. This sucks when entering text. 

I'll include a screenshot: 
![Screenshot_20240303_105041_Firefox Focus](https://github.com/dokuwiki/dokuwiki/assets/81969656/f8003fa8-3818-4abf-937a-f82e6874c683)

### Version of DokuWiki

20220731.a-2 "Igor"

### PHP Version

8.2

### Webserver and version of webserver

apache2 (2.4.57-2) on Debian 12

### Browser and version of browser, operating system running browser

Fennec F-Droid 123.0.0 as well as Firefox Focus 123.0 on Android 14

### Additional environment information

There are multiple templates (bootstrap, bookstack, dokuwiki, vector) available on our instance, and in all of them this layout is broken.

**Comment by fiwswe** [comment]
>20220731.a-2 "Igor"

First, that version does not exist. Did you mean 2022-07-31a "Igor" or maybe 2022-07-31b "Igor"?

Second, assuming this is some version of "Igor", no one is going to fix this old version of DokuWiki. Upgrade to the current version (2024-02-06a "Kaos") and check whether the problem still exists there. If so, update this issue. Otherwise please close it.

See: [Upgrading DokuWiki](https://www.dokuwiki.org/install:upgrade)


>There are multiple templates (bootstrap, bookstack, dokuwiki, vector) available on our instance, and in all of them this layout is broken.

This issue tracker only applies to the DokuWiki template which is a part of DokuWiki. For the other templates you mentioned you'd need to file the issue in their respective issue trackers.

Also make sure you are using the latest versions of the templates before filing an issue.

**Comment by fiwswe** [comment]
BTW: I could **not** reproduce this on iOS 17.3.1 Safari on an iPhone 13 mini using https://dokuwiki.org/playground.

Note: dokuwiki.org uses 2024-02-06a "Kaos" with the DokuWiki template.

**Comment by JohaJung** [comment]
> > 20220731.a-2 "Igor"
> 
> First, that version does not exist. Did you mean 2022-07-31a "Igor" or maybe 2022-07-31b "Igor"?

The one included in Debian 12.

> Second, assuming this is _some version of_ "Igor", no one is going to fix this old version of DokuWiki. Upgrade to the current version (2024-02-06a "Kaos") and check whether the problem still exists there. If so, update this issue. Otherwise please close it.

Indeed, I also found this issue fixed in my Browser with the current version on dokuwiki.org/playground

Thanks for helping out :) 
and sorry for not checking latest version...

**Comment by fiwswe** [comment]
>The one included in Debian 12.

For future reference:
* Add a `do=check` URL parameter (while logged in as an admin) to see the official DokuWiki version number.
* Or check the contents of the file `VERSION` at the root of your DokuWiki directory.

People generally don't know which versions are packaged for any particular OS unless they happen to use that OS themselves.

>Indeed, I also found this issue fixed in my Browser with the current version on dokuwiki.org/playground

👍
