### ISSUE TITLE
auth capability 'login' missing

### ISSUE THREAD

**Issue by splitbrain** [dokuwiki/dokuwiki#797]
As discussed in #702 it makes sense that single sign-on auth backend can disable the login form completely. For this a new `$cando` capability named `login` needs to be added and checked in `actionOK`.

**Comment by janwh** [comment]
Whoa, this has been open for quite a while 😨 

I am currently setting up a DokuWiki instance, using @ivan-novakov's authshibboleth plugin. The afforementioned ivan-novakov/dokuwiki-shibboleth-auth#6 is causing novice users of the platform to be confused about when and where to enter their credentials, and I want to prevent users entering their Shibboleth login info into random form fields.

I started working on this issue and made the most obvious (to me at least – I have no experience in the development of DokuWiki) changes, and noticed some overlapping usage when setting an `&cando['login']` for a plugin, defaulting to false, since `actionOK['login']` also constructs the MenuItem Login/Logout, right? 

Would it be better to create an entirely new capability for the Auth Plugin (something like `&cando['loginForm']`, to avoid collision with 'login'? Or am I thinking in too complicated? I am going to push my current changes asap.

Cheers! 👋

**Comment by janwh** [comment]
Whoa, this has been open for quite a while 😨 

I am currently setting up a DokuWiki instance, using @ivan-novakov's authshibboleth plugin. The afforementioned ivan-novakov/dokuwiki-shibboleth-auth#6 is causing novice users of the platform to be confused about when and where to enter their credentials, and I want to prevent users entering their Shibboleth login info into random form fields.

I started working on this issue and made the most obvious (to me at least – I have no experience in the development of DokuWiki) changes, and noticed some overlapping usage when setting an `&cando['login']` for a plugin, defaulting to false, since `actionOK['login']` also constructs the MenuItem Login/Logout, right? 

Would it be better to create an entirely new capability for the Auth Plugin (something like `&cando['loginForm']`, to avoid collision with 'login'? Or am I thinking in too complicated? I am going to push my current changes asap.

Cheers! 👋
